theme: jekyll-theme-architect

title: [jsr311]
description: [JAX-RS: Java API for RESTful Web Services]

# sidebar links url
links:
  source: https://github.com/javaee/jsr311
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

